name: Docker Image Scan
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Dev
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: oryd/oathkeeper:dev
          load: true
          file: ./Dockerfile
      - name: Build Dev Alpine
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: oryd/oathkeeper:alpine
          load: true
          file: ./Dockerfile-alpine
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          # image: oryd/local-scan:sha-${{ steps.vars.outputs.sha_short }}
          path: "."
          fail-build: true
          severity-cutoff: high
